# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: bice-challenge
# app and org for use with dashboard.serverless.com
app: bice-challenge
org: rodrigobustamante

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  handler:
    handler: handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    environment:
      POLICY_API_URL: https://dn8mlk7hdujby.cloudfront.net/interview/insurance/policy
      POLICY_AGE_LIMIT: 65
      POLICY_PRICES__HEALTH__WITHOUT_CHILDREN: 0.279
      POLICY_PRICES__HEALTH__ONE_CHILD: 0.4396
      POLICY_PRICES__HEALTH__TWO_OR_MORE_CHILDREN: 0.5599
      POLICY_PRICES__DENTAL__WITHOUT_CHILDREN: 0.12
      POLICY_PRICES__DENTAL__ONE_CHILD: 0.1950
      POLICY_PRICES__DENTAL__TWO_OR_MORE_CHILDREN: 0.2480

plugins:
  - serverless-plugin-typescript
  - serverless-offline
